// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: haptic.proto

#include "haptic.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace pb {
namespace Haptic {
class HapticDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Haptic> _instance;
} _Haptic_default_instance_;
}  // namespace Haptic
}  // namespace pb
static void InitDefaultsscc_info_Haptic_haptic_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pb::Haptic::_Haptic_default_instance_;
    new (ptr) ::pb::Haptic::Haptic();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pb::Haptic::Haptic::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Haptic_haptic_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Haptic_haptic_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_haptic_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_haptic_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_haptic_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_haptic_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pb::Haptic::Haptic, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pb::Haptic::Haptic, haptic_state_),
  PROTOBUF_FIELD_OFFSET(::pb::Haptic::Haptic, haptic_offset_),
  PROTOBUF_FIELD_OFFSET(::pb::Haptic::Haptic, haptic_force_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::pb::Haptic::Haptic)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::pb::Haptic::_Haptic_default_instance_),
};

const char descriptor_table_protodef_haptic_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014haptic.proto\022\tpb.Haptic\"K\n\006Haptic\022\024\n\014h"
  "aptic_state\030\001 \001(\002\022\025\n\rhaptic_offset\030\002 \001(\002"
  "\022\024\n\014haptic_force\030\003 \001(\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_haptic_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_haptic_2eproto_sccs[1] = {
  &scc_info_Haptic_haptic_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_haptic_2eproto_once;
static bool descriptor_table_haptic_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_haptic_2eproto = {
  &descriptor_table_haptic_2eproto_initialized, descriptor_table_protodef_haptic_2eproto, "haptic.proto", 110,
  &descriptor_table_haptic_2eproto_once, descriptor_table_haptic_2eproto_sccs, descriptor_table_haptic_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_haptic_2eproto::offsets,
  file_level_metadata_haptic_2eproto, 1, file_level_enum_descriptors_haptic_2eproto, file_level_service_descriptors_haptic_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_haptic_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_haptic_2eproto), true);
namespace pb {
namespace Haptic {

// ===================================================================

void Haptic::InitAsDefaultInstance() {
}
class Haptic::_Internal {
 public:
};

Haptic::Haptic()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.Haptic.Haptic)
}
Haptic::Haptic(const Haptic& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&haptic_state_, &from.haptic_state_,
    static_cast<size_t>(reinterpret_cast<char*>(&haptic_force_) -
    reinterpret_cast<char*>(&haptic_state_)) + sizeof(haptic_force_));
  // @@protoc_insertion_point(copy_constructor:pb.Haptic.Haptic)
}

void Haptic::SharedCtor() {
  ::memset(&haptic_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&haptic_force_) -
      reinterpret_cast<char*>(&haptic_state_)) + sizeof(haptic_force_));
}

Haptic::~Haptic() {
  // @@protoc_insertion_point(destructor:pb.Haptic.Haptic)
  SharedDtor();
}

void Haptic::SharedDtor() {
}

void Haptic::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Haptic& Haptic::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Haptic_haptic_2eproto.base);
  return *internal_default_instance();
}


void Haptic::Clear() {
// @@protoc_insertion_point(message_clear_start:pb.Haptic.Haptic)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&haptic_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&haptic_force_) -
      reinterpret_cast<char*>(&haptic_state_)) + sizeof(haptic_force_));
  _internal_metadata_.Clear();
}

const char* Haptic::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float haptic_state = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          haptic_state_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float haptic_offset = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          haptic_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float haptic_force = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          haptic_force_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Haptic::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.Haptic.Haptic)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float haptic_state = 1;
  if (!(this->haptic_state() <= 0 && this->haptic_state() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_haptic_state(), target);
  }

  // float haptic_offset = 2;
  if (!(this->haptic_offset() <= 0 && this->haptic_offset() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_haptic_offset(), target);
  }

  // float haptic_force = 3;
  if (!(this->haptic_force() <= 0 && this->haptic_force() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_haptic_force(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.Haptic.Haptic)
  return target;
}

size_t Haptic::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb.Haptic.Haptic)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float haptic_state = 1;
  if (!(this->haptic_state() <= 0 && this->haptic_state() >= 0)) {
    total_size += 1 + 4;
  }

  // float haptic_offset = 2;
  if (!(this->haptic_offset() <= 0 && this->haptic_offset() >= 0)) {
    total_size += 1 + 4;
  }

  // float haptic_force = 3;
  if (!(this->haptic_force() <= 0 && this->haptic_force() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Haptic::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pb.Haptic.Haptic)
  GOOGLE_DCHECK_NE(&from, this);
  const Haptic* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Haptic>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pb.Haptic.Haptic)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pb.Haptic.Haptic)
    MergeFrom(*source);
  }
}

void Haptic::MergeFrom(const Haptic& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pb.Haptic.Haptic)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.haptic_state() <= 0 && from.haptic_state() >= 0)) {
    _internal_set_haptic_state(from._internal_haptic_state());
  }
  if (!(from.haptic_offset() <= 0 && from.haptic_offset() >= 0)) {
    _internal_set_haptic_offset(from._internal_haptic_offset());
  }
  if (!(from.haptic_force() <= 0 && from.haptic_force() >= 0)) {
    _internal_set_haptic_force(from._internal_haptic_force());
  }
}

void Haptic::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pb.Haptic.Haptic)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Haptic::CopyFrom(const Haptic& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb.Haptic.Haptic)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Haptic::IsInitialized() const {
  return true;
}

void Haptic::InternalSwap(Haptic* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(haptic_state_, other->haptic_state_);
  swap(haptic_offset_, other->haptic_offset_);
  swap(haptic_force_, other->haptic_force_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Haptic::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Haptic
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::pb::Haptic::Haptic* Arena::CreateMaybeMessage< ::pb::Haptic::Haptic >(Arena* arena) {
  return Arena::CreateInternal< ::pb::Haptic::Haptic >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
